//import './globals.css';
import '../../styles/style.scss';
import Navbar from '../../components/Navbar';

import { Poppins, Montserrat } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] });
const montserrat = Montserrat({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
	title: 'Filantropia EAFIT',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
